// Command event types for FFI boundary

use super::types::BsonBytes;
use std::ffi::CString;
use std::os::raw::c_char;
use std::sync::atomic::{AtomicI64, Ordering};

/// Global atomic counter for generating operation IDs
/// The Rust MongoDB driver doesn't provide operationId, so we generate it ourselves
static OPERATION_ID_COUNTER: AtomicI64 = AtomicI64::new(1);

/// Command event type discriminant
#[repr(C)]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommandEventType {
    Started = 0,
    Succeeded = 1,
    Failed = 2,
}

/// Connection information matching Rust driver's ConnectionInfo
/// Simplified compared to Java's ConnectionDescription
#[repr(C)]
pub struct FfiConnectionInfo {
    /// Driver-generated connection ID
    pub connection_id: u32,
    /// Server-generated connection ID (-1 if not present)
    pub server_connection_id: i64,
    /// Whether server_connection_id is present
    pub server_connection_id_present: bool,
    /// Host address (null-terminated string)
    pub host: *const c_char,
    /// Port number
    pub port: u16,
    /// Service ID bytes (ObjectId, 12 bytes, zeroed if not present)
    pub service_id: [u8; 12],
    /// Whether service_id is present
    pub service_id_present: bool,
}

impl Default for FfiConnectionInfo {
    fn default() -> Self {
        Self {
            connection_id: 0,
            server_connection_id: -1,
            server_connection_id_present: false,
            host: std::ptr::null(),
            port: 0,
            service_id: [0u8; 12],
            service_id_present: false,
        }
    }
}

/// Union-like struct for all command event types
/// Unused fields are zeroed/null for a given event type
#[repr(C)]
pub struct FfiCommandEvent {
    /// Event type discriminant (Started=0, Succeeded=1, Failed=2)
    pub event_type: CommandEventType,
    /// Driver-generated request ID (correlates started/succeeded/failed)
    pub request_id: i32,
    /// Operation ID (generated by our FFI layer, groups related commands)
    pub operation_id: i64,
    /// Connection information
    pub connection: FfiConnectionInfo,
    /// Database name (null-terminated)
    pub database: *const c_char,
    /// Command name (null-terminated), e.g. "find", "insert"
    pub command_name: *const c_char,
    /// For Started: the command document (BSON bytes)
    pub command: BsonBytes,
    /// For Succeeded: the response document (BSON bytes)
    pub response: BsonBytes,
    /// For Succeeded/Failed: elapsed time in nanoseconds
    pub elapsed_nanos: i64,
    /// For Failed: error message (null-terminated)
    pub error_message: *const c_char,
}

impl Default for FfiCommandEvent {
    fn default() -> Self {
        Self {
            event_type: CommandEventType::Started,
            request_id: 0,
            operation_id: 0,
            connection: FfiConnectionInfo::default(),
            database: std::ptr::null(),
            command_name: std::ptr::null(),
            command: BsonBytes {
                data: std::ptr::null(),
                len: 0,
            },
            response: BsonBytes {
                data: std::ptr::null(),
                len: 0,
            },
            elapsed_nanos: 0,
            error_message: std::ptr::null(),
        }
    }
}

/// Callback function type for command events (non-nullable)
/// This is the actual function signature that Java implements
pub type CommandEventCallbackFn = extern "C" fn(event: *const FfiCommandEvent);

/// Nullable callback type for command events
/// Java implements this and passes to Rust during client creation
/// cbindgen should translate Option<extern "C" fn(...)> to a nullable C function pointer
pub type CommandEventCallback = Option<extern "C" fn(event: *const FfiCommandEvent)>;

/// Generate a new unique operation ID
pub fn generate_operation_id() -> i64 {
    OPERATION_ID_COUNTER.fetch_add(1, Ordering::SeqCst)
}

/// Create an EventHandler that forwards command events to the Java callback
///
/// This function creates a Rust driver EventHandler that:
/// 1. Receives CommandEvent from the Rust driver
/// 2. Converts it to FfiCommandEvent (our C-compatible struct)
/// 3. Calls the Java callback with a pointer to the FFI event
///
/// # Safety
/// The callback must remain valid for the lifetime of the EventHandler.
/// The callback is called synchronously, so any data pointed to by FfiCommandEvent
/// is only valid during the callback invocation.
/// Note: This function takes the unwrapped function type (not Option), as the caller
/// has already verified the callback is Some.
pub fn create_command_event_handler(
    callback: CommandEventCallbackFn,
) -> crate::event::EventHandler<crate::event::command::CommandEvent> {
    use crate::event::{command::CommandEvent, EventHandler};

    // Generate a shared operation ID for this handler
    // NOTE: In a real implementation, we'd want to track request_id -> operation_id mapping
    // For now, we use a simple approach where each event gets a new operation_id
    // TODO: Implement proper operation_id tracking based on request_id correlation

    EventHandler::callback(move |event: CommandEvent| {
        // Convert the Rust event to our FFI structure and invoke callback
        match &event {
            CommandEvent::Started(e) => convert_started_event(e, callback),
            CommandEvent::Succeeded(e) => convert_succeeded_event(e, callback),
            CommandEvent::Failed(e) => convert_failed_event(e, callback),
            _ => {} // Handle any future variants gracefully
        }
    })
}

/// Convert CommandStartedEvent to FfiCommandEvent and invoke callback
fn convert_started_event(
    event: &crate::event::command::CommandStartedEvent,
    callback: CommandEventCallbackFn,
) {
    // Prepare strings - these must live until after the callback returns
    let db_cstring = CString::new(event.db.as_str()).unwrap_or_default();
    let cmd_name_cstring = CString::new(event.command_name.as_str()).unwrap_or_default();
    let host_cstring = CString::new(event.connection.address.to_string()).unwrap_or_default();

    // Serialize command Document to BSON bytes
    let command_bytes: Vec<u8> = crate::bson::to_vec(&event.command).unwrap_or_default();

    // Build connection info
    let connection_info =
        build_connection_info(&event.connection, &event.service_id, &host_cstring);

    // Build the FFI event
    let ffi_event = FfiCommandEvent {
        event_type: CommandEventType::Started,
        request_id: event.request_id,
        operation_id: generate_operation_id(), // TODO: Track by request_id for correlation
        connection: connection_info,
        database: db_cstring.as_ptr(),
        command_name: cmd_name_cstring.as_ptr(),
        command: BsonBytes {
            data: command_bytes.as_ptr(),
            len: command_bytes.len(),
        },
        response: BsonBytes {
            data: std::ptr::null(),
            len: 0,
        },
        elapsed_nanos: 0,
        error_message: std::ptr::null(),
    };

    // Invoke the Java callback
    callback(&ffi_event);

    // All CStrings and Vec are dropped here after callback returns
}

/// Convert CommandSucceededEvent to FfiCommandEvent and invoke callback
/// NOTE: CommandSucceededEvent doesn't have a `db` field - we pass empty string
fn convert_succeeded_event(
    event: &crate::event::command::CommandSucceededEvent,
    callback: CommandEventCallbackFn,
) {
    // Prepare strings - NOTE: db is not available in CommandSucceededEvent
    let db_cstring = CString::new("").unwrap_or_default();
    let cmd_name_cstring = CString::new(event.command_name.as_str()).unwrap_or_default();
    let host_cstring = CString::new(event.connection.address.to_string()).unwrap_or_default();

    // Serialize reply Document to BSON bytes
    let reply_bytes: Vec<u8> = crate::bson::to_vec(&event.reply).unwrap_or_default();

    // Build connection info
    let connection_info =
        build_connection_info(&event.connection, &event.service_id, &host_cstring);

    // Build the FFI event
    let ffi_event = FfiCommandEvent {
        event_type: CommandEventType::Succeeded,
        request_id: event.request_id,
        operation_id: generate_operation_id(), // TODO: Track by request_id for correlation
        connection: connection_info,
        database: db_cstring.as_ptr(),
        command_name: cmd_name_cstring.as_ptr(),
        command: BsonBytes {
            data: std::ptr::null(),
            len: 0,
        },
        response: BsonBytes {
            data: reply_bytes.as_ptr(),
            len: reply_bytes.len(),
        },
        elapsed_nanos: event.duration.as_nanos() as i64,
        error_message: std::ptr::null(),
    };

    // Invoke the Java callback
    callback(&ffi_event);
}

/// Convert CommandFailedEvent to FfiCommandEvent and invoke callback
/// NOTE: CommandFailedEvent doesn't have a `db` field - we pass empty string
fn convert_failed_event(
    event: &crate::event::command::CommandFailedEvent,
    callback: CommandEventCallbackFn,
) {
    // Prepare strings - NOTE: db is not available in CommandFailedEvent
    let db_cstring = CString::new("").unwrap_or_default();
    let cmd_name_cstring = CString::new(event.command_name.as_str()).unwrap_or_default();
    let host_cstring = CString::new(event.connection.address.to_string()).unwrap_or_default();
    let error_cstring = CString::new(event.failure.to_string()).unwrap_or_default();

    // Build connection info
    let connection_info =
        build_connection_info(&event.connection, &event.service_id, &host_cstring);

    // Build the FFI event
    let ffi_event = FfiCommandEvent {
        event_type: CommandEventType::Failed,
        request_id: event.request_id,
        operation_id: generate_operation_id(), // TODO: Track by request_id for correlation
        connection: connection_info,
        database: db_cstring.as_ptr(),
        command_name: cmd_name_cstring.as_ptr(),
        command: BsonBytes {
            data: std::ptr::null(),
            len: 0,
        },
        response: BsonBytes {
            data: std::ptr::null(),
            len: 0,
        },
        elapsed_nanos: event.duration.as_nanos() as i64,
        error_message: error_cstring.as_ptr(),
    };

    // Invoke the Java callback
    callback(&ffi_event);
}

/// Build FfiConnectionInfo from Rust driver's ConnectionInfo
fn build_connection_info(
    conn: &crate::event::command::ConnectionInfo,
    service_id: &Option<crate::bson::oid::ObjectId>,
    host_cstring: &CString,
) -> FfiConnectionInfo {
    // Parse address to get port (default to 27017 if not specified)
    let port: u16 = match &conn.address {
        crate::options::ServerAddress::Tcp { host: _, port } => port.unwrap_or(27017),
        #[allow(unreachable_patterns)]
        _ => 27017,
    };

    // Build service_id bytes
    let (service_id_bytes, service_id_present) = match service_id {
        Some(oid) => (oid.bytes(), true),
        None => ([0u8; 12], false),
    };

    FfiConnectionInfo {
        connection_id: conn.id,
        server_connection_id: conn.server_id.unwrap_or(-1),
        server_connection_id_present: conn.server_id.is_some(),
        host: host_cstring.as_ptr(),
        port,
        service_id: service_id_bytes,
        service_id_present,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::atomic::{AtomicUsize, Ordering as AtomicOrdering};

    #[test]
    fn test_event_type_values() {
        assert_eq!(CommandEventType::Started as i32, 0);
        assert_eq!(CommandEventType::Succeeded as i32, 1);
        assert_eq!(CommandEventType::Failed as i32, 2);
    }

    #[test]
    fn test_connection_info_size() {
        // Ensure the struct has a stable layout
        // connection_id(4) + padding(4) + server_connection_id(8) + present(1) + padding(7)
        // + host(8) + port(2) + padding(6) + service_id(12) + present(1) + padding(3)
        // This is approximate - actual size depends on platform alignment
        let size = std::mem::size_of::<FfiConnectionInfo>();
        println!("FfiConnectionInfo size: {}", size);
        assert!(size > 0);
    }

    /// Test that command events actually fire when executing a command
    /// This test requires a MongoDB instance running on localhost:27017
    #[test]
    fn test_command_events_fire() {
        use crate::bson::doc;

        // Counter for events received
        static EVENT_COUNT: AtomicUsize = AtomicUsize::new(0);

        // Callback that increments the counter
        extern "C" fn test_callback(event: *const FfiCommandEvent) {
            if !event.is_null() {
                let e = unsafe { &*event };
                println!("Received event type: {:?}", e.event_type);
                EVENT_COUNT.fetch_add(1, AtomicOrdering::SeqCst);
            }
        }

        // Create a Tokio runtime
        let runtime = tokio::runtime::Runtime::new().expect("Failed to create runtime");

        // Build client options with event handler
        let mut options = crate::options::ClientOptions::default();
        options.hosts = vec!["localhost:27017".parse().unwrap()];
        options.command_event_handler = Some(create_command_event_handler(test_callback));

        // Create client and execute a command
        runtime.block_on(async {
            let client = crate::Client::with_options(options).expect("Failed to create client");
            let db = client.database("admin");

            // Execute a ping command - should trigger Started and Succeeded events
            let result = db.run_command(doc! { "ping": 1 }).await;
            println!("Ping result: {:?}", result);
            assert!(result.is_ok(), "Ping should succeed");
        });

        // Check that we received events
        let count = EVENT_COUNT.load(AtomicOrdering::SeqCst);
        println!("Total events received: {}", count);
        assert!(
            count >= 2,
            "Should have received at least Started and Succeeded events"
        );
    }
}
