/*
 * MongoDB Rust Driver FFI - Auto-generated C header
 *
 * This header is generated by cbindgen from the Rust FFI module.
 * Do not edit manually.
 *
 * Usage:
 *   1. Link against libmongodb.so / libmongodb.dylib / mongodb.dll
 *   2. Include this header
 *   3. Call mongo_client_new() to create a client
 *
 * Thread safety:
 *   - MongoClient handles are thread-safe
 *   - Callbacks may be invoked from any thread
 */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
// Forward declaration of opaque client type
struct MongoClient;


// Log level constants matching Java's LogMessage.Level
#define LOG_LEVEL_DEBUG 0

#define LOG_LEVEL_INFO 1

#define ERROR_CATEGORY_COMMAND 0

#define ERROR_CATEGORY_CONNECTION 1

#define ERROR_CATEGORY_SERVER_SELECTION 2

#define ERROR_CATEGORY_AUTHENTICATION 3

#define ERROR_CATEGORY_INTERNAL 4

// Command event type discriminant
typedef enum CommandEventType {
  STARTED = 0,
  SUCCEEDED = 1,
  FAILED = 2,
} CommandEventType;

// Raw BSON bytes passed across FFI boundary
typedef struct BsonBytes {
  const uint8_t *data;
  uintptr_t len;
} BsonBytes;

// A single log field (name/value pair)
typedef struct FfiLogField {
  const char *name;
  const char *value;
} FfiLogField;

// Log event structure passed to Java callback
typedef struct FfiLogEvent {
  // Log level: 0=DEBUG, 1=INFO
  int32_t level;
  // Tracing target: "crate::command", "crate::connection", etc.
  const char *target;
  // Message identifier: "Command started", "Connection pool created", etc.
  const char *message;
  // Number of fields
  int32_t field_count;
  // Array of fields
  const struct FfiLogField *fields;
} FfiLogEvent;

// Callback type for log events (C FFI / JNA)
// Java implements this and passes to Rust via init_logging()
typedef void (*LogCallback)(const struct FfiLogEvent *event);

// Connection/topology settings passed from Java.
// Must match the layout of ConnectionSettings.java.
typedef struct ConnectionSettings {
  // Array of host:port strings (e.g., "localhost:27017")
  const char *const *hosts;
  // Number of hosts in the array
  int32_t hosts_len;
  // Whether to connect directly to a single host
  // 0 = not set, 1 = false, 2 = true
  uint8_t direct_connection;
  // Replica set name (null-terminated C string)
  const char *repl_set_name;
  // SRV service name (null-terminated C string)
  const char *srv_service_name;
  // Maximum number of SRV hosts (0 if not set)
  uint32_t srv_max_hosts;
  // Server selection timeout in milliseconds (0 if not set)
  uint64_t server_selection_timeout_ms;
  // Local threshold in milliseconds (0 if not set)
  uint64_t local_threshold_ms;
  // Whether this is a load-balanced topology
  // 0 = not set, 1 = false, 2 = true
  uint8_t load_balanced;
} ConnectionSettings;

// Authentication settings passed from Java.
// Must match the layout of AuthSettings.java.
typedef struct AuthSettings {
  // Authentication mechanism (e.g., "SCRAM-SHA-256")
  const char *mechanism;
  // Authentication source database
  const char *source;
  // Username
  const char *username;
  // Password
  const char *password;
  // Array of mechanism properties as key=value strings
  const char *const *mechanism_properties;
  // Number of mechanism properties
  int32_t mechanism_properties_len;
} AuthSettings;

// TLS/SSL settings passed from Java.
// Must match the layout of TlsSettings.java.
typedef struct TlsSettings {
  // Whether TLS is enabled (0 = disabled, 1 = enabled)
  uint8_t enabled;
  // Whether to allow invalid certificates
  // 0 = not set, 1 = false, 2 = true
  uint8_t allow_invalid_certificates;
  // Whether to allow invalid hostnames
  // 0 = not set, 1 = false, 2 = true
  uint8_t allow_invalid_hostnames;
  // Path to CA certificate file
  const char *ca_file_path;
  // Path to client certificate/key file
  const char *cert_key_file_path;
} TlsSettings;

// Connection information matching Rust driver's ConnectionInfo
// Simplified compared to Java's ConnectionDescription
typedef struct FfiConnectionInfo {
  // Driver-generated connection ID
  uint32_t connection_id;
  // Server-generated connection ID (-1 if not present)
  int64_t server_connection_id;
  // Whether server_connection_id is present
  bool server_connection_id_present;
  // Host address (null-terminated string)
  const char *host;
  // Port number
  uint16_t port;
  // Service ID bytes (ObjectId, 12 bytes, zeroed if not present)
  uint8_t service_id[12];
  // Whether service_id is present
  bool service_id_present;
} FfiConnectionInfo;

// Union-like struct for all command event types
// Unused fields are zeroed/null for a given event type
typedef struct FfiCommandEvent {
  // Event type discriminant (Started=0, Succeeded=1, Failed=2)
  enum CommandEventType event_type;
  // Driver-generated request ID (correlates started/succeeded/failed)
  int32_t request_id;
  // Operation ID (generated by our FFI layer, groups related commands)
  int64_t operation_id;
  // Connection information
  struct FfiConnectionInfo connection;
  // Database name (null-terminated)
  const char *database;
  // Command name (null-terminated), e.g. "find", "insert"
  const char *command_name;
  // For Started: the command document (BSON bytes)
  struct BsonBytes command;
  // For Succeeded: the response document (BSON bytes)
  struct BsonBytes response;
  // For Succeeded/Failed: elapsed time in nanoseconds
  int64_t elapsed_nanos;
  // For Failed: error message (null-terminated)
  const char *error_message;
} FfiCommandEvent;

// Nullable callback type for command events
// Java implements this and passes to Rust during client creation
// cbindgen should translate Option<extern "C" fn(...)> to a nullable C function pointer
typedef void (*CommandEventCallback)(const struct FfiCommandEvent *event);

// Callback for single result operations
//
// # Parameters
// * `success` - Whether the operation succeeded
// * `data` - BSON bytes for the result (if success=true) or error (if success=false)
typedef void (*SingleResultCallback)(bool success, const struct BsonBytes *data);

// Operation context passed across FFI boundary
// Contains session, transaction, and retryability information
typedef struct OperationContext {
  // Retryability: 0=None, 1=Read, 2=Write
  uint8_t retryability;
  // Session handle from mongo_session_acquire (0 = no session)
  uint64_t session_handle;
  // Whether the operation is in a transaction
  bool in_transaction;
  // Whether to start a new transaction
  bool start_transaction;
  // Whether afterClusterTime is set
  bool has_after_cluster_time;
  // afterClusterTime seconds component (only valid if has_after_cluster_time is true)
  uint32_t after_cluster_time_seconds;
  // afterClusterTime increment component (only valid if has_after_cluster_time is true)
  uint32_t after_cluster_time_increment;
  // Read concern level (nullable, null-terminated C string)
  const char *read_concern_level;
} OperationContext;

// Callback for cursor operations
//
// # Parameters
// * `success` - Whether the operation succeeded
// * `cursor_handle` - Handle to the cursor (0 on error)
// * `exhausted` - Whether the cursor is exhausted (no more batches)
// * `data` - BSON bytes for the batch (firstBatch or nextBatch)
typedef void (*CursorResultCallback)(bool success,
                                     uint64_t cursor_handle,
                                     bool exhausted,
                                     const struct BsonBytes *data);

// Callback for getMore operations
//
// # Parameters
// * `success` - Whether the operation succeeded
// * `exhausted` - Whether the cursor is exhausted (no more batches)
// * `data` - BSON bytes for the nextBatch
typedef void (*GetMoreResultCallback)(bool success, bool exhausted, const struct BsonBytes *data);

// Acquire a session from the client's session pool.
// Returns a session handle (non-zero), or 0 on error.
uint64_t mongo_session_acquire(struct MongoClient *client);

// Release a session back to the client's session pool.
void mongo_session_release(struct MongoClient *client, uint64_t session_handle);

// Get the transaction number for a session.
int64_t mongo_session_get_txn_number(struct MongoClient *client, uint64_t session_handle);

// Advance the transaction number and return the new value.
int64_t mongo_session_advance_txn_number(struct MongoClient *client, uint64_t session_handle);

// Mark a session as dirty (should not be returned to pool).
void mongo_session_mark_dirty(struct MongoClient *client, uint64_t session_handle);

// Get the session lsid as BSON bytes.
// Caller must call mongo_free_bytes on the returned data when done.
// Returns BsonBytes with null data if session not found.
struct BsonBytes mongo_session_get_lsid(struct MongoClient *client, uint64_t session_handle);

// Free bytes allocated by Rust (e.g., from mongo_session_get_lsid).
void mongo_free_bytes(uint8_t *data, uintptr_t len);

// Initialize logging globally with a callback and per-component log levels.
// This should be called once at first client creation.
//
// Log levels: 0 = DEBUG, 1 = INFO, 2 = WARN (effectively disabled)
//
// NOTE: callback MUST be the last parameter for JNA compatibility
void mongo_init_logging(int32_t command_level,
                        int32_t connection_level,
                        int32_t server_selection_level,
                        int32_t topology_level,
                        LogCallback callback);

// Update log levels at runtime.
// Can be called periodically to refresh levels from SLF4J.
//
// Log levels: 0 = DEBUG, 1 = INFO, 2 = WARN (effectively disabled)
//
// NOTE: Due to tracing limitations, the filter is fixed at init time.
// This function is provided for API completeness.
void mongo_update_log_levels(int32_t command_level,
                             int32_t connection_level,
                             int32_t server_selection_level,
                             int32_t topology_level);

// Create a new MongoDB client with settings structs
// NOTE: All settings are passed by reference (pointer) for JNA compatibility
// NOTE: Callbacks must be the LAST parameters for JNA compatibility
// NOTE: Logging is now initialized globally via mongo_init_logging()
// NOTE: max_document_length controls log truncation per-client
// NOTE: command_event_callback can be NULL if no event monitoring is needed
struct MongoClient *mongo_client_new(const struct ConnectionSettings *connection_settings,
                                     const struct AuthSettings *auth_settings,
                                     const struct TlsSettings *tls_settings,
                                     int32_t max_document_length,
                                     CommandEventCallback command_event_callback);

// Destroy a MongoDB client
void mongo_client_destroy(struct MongoClient *client);

// Enable timing (call from Java via FFI)
void mongo_enable_timing(bool enabled);

// No-op FFI function to measure pure FFI overhead (spawn + callback, no MongoDB)
void mongo_ffi_overhead_test(struct MongoClient *client,
                             const struct BsonBytes *input,
                             SingleResultCallback callback);

// Print FFI overhead stats
void mongo_print_ffi_overhead_stats(void);

// Print timing stats to stderr
void mongo_print_timing_stats(void);

// Execute a command using session handle (matches JNI executeCommandAsync).
// Rust looks up the session by handle and manages lsid/txnNumber internally.
//
// Parameters:
// - client: The MongoClient pointer
// - database: Database name (null-terminated C string)
// - command: BSON command bytes
// - context: Operation context with session, transaction, and retryability info
// - callback: Callback to invoke with result
void mongo_execute_command(struct MongoClient *client,
                           const char *database,
                           const struct BsonBytes *command,
                           const struct OperationContext *context,
                           SingleResultCallback callback);

// Execute a cursor-returning command (find, aggregate, listCollections, etc.)
// Returns cursor handle, exhausted flag, and first batch via callback.
//
// Parameters:
// - client: The MongoClient pointer
// - database: Database name (null-terminated C string)
// - command: BSON command bytes
// - batch_size: Batch size for getMore operations (0 = use server default)
// - context: Operation context with session, transaction, and retryability info
// - callback: Callback to invoke with result
void mongo_execute_cursor_command(struct MongoClient *client,
                                  const char *database,
                                  const struct BsonBytes *command,
                                  int32_t batch_size,
                                  const struct OperationContext *context,
                                  CursorResultCallback callback);

// Execute getMore on a cursor (get next batch).
// Returns exhausted flag and next batch via callback.
//
// Parameters:
// - client: The MongoClient pointer
// - cursor_handle: Handle to the cursor
// - callback: Callback to invoke with result
void mongo_cursor_get_more(struct MongoClient *client,
                           uint64_t cursor_handle,
                           GetMoreResultCallback callback);

// Close a cursor and clean up resources.
// The RawBatchCursor's Drop impl handles killCursors automatically.
//
// Parameters:
// - client: The MongoClient pointer
// - cursor_handle: Handle to the cursor
// - callback: Callback to invoke on completion
void mongo_cursor_close(struct MongoClient *client,
                        uint64_t cursor_handle,
                        SingleResultCallback callback);

/* End of auto-generated header */
